### ISSUE TITLE
Illuminate Support Version

### ISSUE THREAD

**Issue by markcameron** [that0n3guy/transliteration#1]
Hi,

Could you tag your latest dev-master version of the package to 1.0.1, like that I don't need to require the dev master version, and can continue with 1.0.*. And then it will play nice with laravel 4.2. I require it in one of my packages and would prefer not to run it on dev-master.

Thanks

**Comment by that0n3guy** [comment]
Done!

**Comment by markcameron** [comment]
Thanks, care to do a "Force Update" on Packagist as well?

**Comment by that0n3guy** [comment]
Yup, done... .need to setup auto update someday.

**Comment by markcameron** [comment]
Thanks! Indeed, quite handy!

**Comment by markcameron** [comment]
@that0n3guy 
Been making some modifications to get it working with Laravel 6.0 (and then i'll do 7.0). I managed to use up my 1 force update on packagist as a guest, don't know how long the timeout is. If you could either setup the auto update according to one of the methods here: https://packagist.org/about#how-to-update-packages that would be great.

Otherwise a manual update would work for now. Don't know if there's a different level of access to the repo that you can give me that allows for that integration to be setup.

Thanks
